version: '3.9'

services:

  sqlserver:
    restart: always
    ports: []  

  nexus_web:
    build:
      context: .
      dockerfile: src/Nexus.Web/Dockerfile
    container_name: nexus_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - nexus_network
    restart: always